---
- name: install_mongodb
  hosts: all
  become: true
  tasks:
    - name: Add unit file for Puma
      apt_key:
           keyserver:  keyserver.ubuntu.com
           id: EA312927
    - name: add mongodb repo
      apt_repository:
         repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
         state: present
         filename: mongodb-org-3.2.list
    - name: Install mongodb package
      apt:
         name: mongodb-org
         state: present
    - name: Configure service mongo
      systemd:
         name: mongod
         enabled: yes



#apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
#bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'
#
#apt update
#apt install -y mongodb-org
#
#systemctl start mongod
#systemctl enable mongod
#systemctl status mongod
